[tool.poetry]
name = "global-greeter"
version = "0.1.0"
description = ""
authors = ["Richard <zohassadar@gmail.com>"]
readme = "README.md"
packages = [{include = "global_greeter", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
